### ISSUE TITLE
Panopticon crashes without settings for Akka

### ISSUE THREAD

**Issue by jczuchnowski** [ScalaConsultants/panopticon-tui#37]
When running Panopticon for ZIO only, it still tries to get Akka diagnostics. This results in a crash:
```
backtrace::backtrace::trace_unsynchronized
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod   
2: std::sys_common::backtrace::_print_fmt stack backtrace: at src/libstd/sys_common/backtrace.rs:84
3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt at src/libstd/sys_common/backtrace.rs:61
4: core::fmt::write at src/libcore/fmt/mod.rs:1025
5: std::io::Write::write_fmt at src/libstd/io/mod.rs:1426
6: std::sys_common::backtrace::_print at src/libstd/sys_common/backtrace.rs:65
7: std::sys_common::backtrace::print at src/libstd/sys_common/backtrace.rs:50
8: std::panicking::default_hook::{{closure}} at src/libstd/panicking.rs:193
9: std::panicking::default_hook at src/libstd/panicking.rs:210
10: std::panicking::rust_panic_with_hook at src/libstd/panicking.rs:471
11: rust_begin_unwind at src/libstd/panicking.rs:375
12: core::panicking::panic_fmt at src/libcore/panicking.rs:84
13: core::panicking::panic at src/libcore/panicking.rs:51
14: core::option::Option<T>::unwrap at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15
15: panopticon_tui::fetcher::Fetcher::get_dead_letters at src/fetcher.rs:106
16: panopticon_tui::main::{{closure}} at src/main.rs:186
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: "SendError(..)"

0: failure::backtrace::internal::InternalBacktrace::new at /home/giacomo/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.7/src/backtrace/internal.rs:46
1: failure::backtrace::Backtrace::new at /home/giacomo/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.7/src/backtrace/mod.rs:121
2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from at /home/giacomo/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.7/src/error/error_impl.rs:19
3: <failure::error::Error as core::convert::From<F>>::from at /home/giacomo/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.7/src/error/mod.rs:36
4: panopticon_tui::main at src/main.rs:302
5: std::rt::lang_start::{{closure}} at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
6: std::rt::lang_start_internal::{{closure}} at src/libstd/rt.rs:52
std::panicking::try::do_call at src/libstd/panicking.rs:292
7: __rust_maybe_catch_panic at src/libpanic_unwind/lib.rs:78
8: std::panicking::try at src/libstd/panicking.rs:270
std::panic::catch_unwind at src/libstd/panic.rs:394
std::rt::lang_start_internal at src/libstd/rt.rs:51
9: std::rt::lang_start at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
10: main
11: __libc_start_main
12: _start
```

**Comment by vpavkin** [comment]
yep, my bad - misplaced the deadletters request. fix coming in a couple of minutes
